# Generated by Django 5.1.6 on 2025-03-07 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255, verbose_name='نام مشتری')),
                ('feedback', models.TextField(verbose_name='نظر')),
                ('rating', models.PositiveIntegerField(default=5, verbose_name='امتیاز')),
                ('image', models.ImageField(blank=True, null=True, upload_to='testimonials/', verbose_name='تصویر مشتری')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'نظر مشتری',
                'verbose_name_plural': 'نظرات مشتریان',
            },
        ),
    ]
